### ISSUE TITLE
Errors when trying to determine mount status of private mounts

### ISSUE THREAD

**Issue by warrenpnz** [GeoffWilliams/puppet-mount_windows_smb#2]
When another user is logged on to Windows machine and mounts a drive that they have used their own credentials for, an error is raised where it says 'Network connection cannot be found'.

Testing showed that the Get-WMIObject for win32_mappedlogicaldisks showed all drives mounted for all users, including the one under theor personal creds. Subsequently the 'net use' command fails with 'The network connection could not be found'. 

Possibly needs a handler for the failure in the provider script

**Comment by GeoffWilliams** [comment]
So just ignore the error, print a warning and continue right? That sounds like the most practical workaround. Good catch.

Want to have a go at a pull request of for this? Happy to merge + release if you come up with something but working on other projects at the moment

**Comment by GeoffWilliams** [comment]
fixed by #3
